### PR TITLE
add bower.json

### PR DESCRIPTION
**Pull request by T1st3**
Add bower.json to the project. The goal is to make the icons available on [Bower](http://bower.io).

After this PR, registration on Bower can be made with:

    bower register geomicons-open git://github.com/jxnblk/geomicons-open.git

### CODE REVIEW

**Comment by T1st3** [comment]
at the moment, you can get this project through Bower these 2 ways:

* on your CLI
    bower install git://github.com/jxnblk/geomicons-open.git#master

* in your bower.json in `dependencies` or `devDependencies`
```
    "dependencies": {
      "geomicons-open": "jxnblk/geomicons-open#master"
    }
```
and then run
    bower install

**Comment by jxnblk** [comment]
Thanks! Sorry I missed this earlier. I'll set up a node script later to keep bower.json in sync with npm.

**Comment by T1st3** [comment]
@jxnblk , thanks form merging.

We still to register the package on the Bower registry:

    bower register geomicons-open git://github.com/jxnblk/geomicons-open.git

But since Bower works with Git tags, it will take the code of your last tag (0.2.0), which is "made-before-this-PR-code", as a first release. Then, I would suggest to create a new tag (say 0.2.1) before a registration on the Bower registry.

Then, after registration, as an update of my previous comment, you would install geomicons via Bower these 2 ways:

* on your CLI
    bower install geomicons-open

* in your bower.json in `dependencies` or `devDependencies`
```
    "dependencies": {
      "geomicons-open": "~0.2"
    }
```
and then run
     bower install

**Comment by jxnblk** [comment]
Lol. Bower is such a pain in the ass. Also BTW, there was a typo here: https://github.com/jxnblk/geomicons-open/pull/55/files#diff-0a08a7565aba4405282251491979bb6bR7

**Comment by T1st3** [comment]
yes, sorry for that one, it's true Bower users will preferably use minified version! Thanks for noticing.

And also true that Bower is not as straightforward as NPM, you're definitely right!

**Pull request merged**
